# Generated by Django 4.1.2 on 2022-11-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_log', models.TextField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('period', models.CharField(max_length=2)),
                ('id_teacher', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=3)),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('id_subject_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academic.subjectperiod')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subjectperiod',
            constraint=models.UniqueConstraint(fields=('year', 'period', 'group', 'id_subject'), name='unique_class'),
        ),
    ]
