# Generated by Django 4.1.2 on 2022-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectperiod',
            name='id_teacher',
            field=models.IntegerField(),
        ),
    ]
